import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  const ire = await prisma.tipoClassificacao.create({ data: { descricao: 'Ire' } })
  const ayewoo = await prisma.tipoClassificacao.create({ data: { descricao: 'Ayewoo' } })

  await prisma.origem.createMany({
    data: [{ descricao: 'Céu' }, { descricao: 'Terra' }],
  })

  await prisma.consulente.createMany({
    data: [{ nome: 'Fabrizio' }, { nome: 'Victor' }, { nome: 'Guilherme' }, { nome: 'Katia' }, { nome: 'Felipe' }, { nome: 'Kate' }, { nome: 'D. Lourdes' }],
  })

  await prisma.tipoConsulta.createMany({
    data: [
      { descricao: 'Diária' },
      { descricao: 'Anual' },
      { descricao: 'Sonho' },
      { descricao: 'Sensação' },
      { descricao: 'Dúvida' },
      { descricao: 'Situação' },
      { descricao: 'Outro' },
    ],
  })

  await prisma.oduIfa.createMany({
    data: [
      { descricao: 'Ogbe Meji' },
      { descricao: 'Oyeku Meji' },
      { descricao: 'Iwori Meji' },
      { descricao: 'Odi Meji' },
      { descricao: 'Irosun Meji' },
      { descricao: 'Oworin Meji' },
      { descricao: 'Obara Meji' },
      { descricao: 'Okanran Meji' },
      { descricao: 'Ogunda Meji' },
      { descricao: 'Osa Meji' },
      { descricao: 'Ika Meji' },
      { descricao: 'Oturupon Meji' },
      { descricao: 'Otura Meji' },
      { descricao: 'Irete Meji' },
      { descricao: 'Ose Meji' },
      { descricao: 'Ofun Meji' },
      { descricao: 'Ogbe Oyeku' },
      { descricao: 'Ogbe Iwori' },
      { descricao: 'Ogbe Odi' },
      { descricao: 'Ogbe Irosun' },
      { descricao: 'Ogbe Oworin' },
      { descricao: 'Ogbe Obara' },
      { descricao: 'Ogbe Okanran' },
      { descricao: 'Ogbe Ogunda' },
      { descricao: 'Ogbe Osa' },
      { descricao: 'Ogbe Ika' },
      { descricao: 'Ogbe Oturupon' },
      { descricao: 'Ogbe Otura' },
      { descricao: 'Ogbe Irete' },
      { descricao: 'Ogbe Ose' },
      { descricao: 'Ogbe Ofun' },
      { descricao: 'Oyeku Ogbe' },
      { descricao: 'Oyeku Iwori' },
      { descricao: 'Oyeku Odi' },
      { descricao: 'Oyeku Irosun' },
      { descricao: 'Oyeku Oworin' },
      { descricao: 'Oyeku Obara' },
      { descricao: 'Oyeku Okanran' },
      { descricao: 'Oyeku Ogunda' },
      { descricao: 'Oyeku Osa' },
      { descricao: 'Oyeku Ika' },
      { descricao: 'Oyeku Oturupon' },
      { descricao: 'Oyeku Otura' },
      { descricao: 'Oyeku Irete' },
      { descricao: 'Oyeku Ose' },
      { descricao: 'Oyeku Ofun' },
      { descricao: 'Iwori Ogbe' },
      { descricao: 'Iwori Oyeku' },
      { descricao: 'Iwori Odi' },
      { descricao: 'Iwori Irosun' },
      { descricao: 'Iwori Oworin' },
      { descricao: 'Iwori Obara' },
      { descricao: 'Iwori Okanran' },
      { descricao: 'Iwori Ogunda' },
      { descricao: 'Iwori Osa' },
      { descricao: 'Iwori Ika' },
      { descricao: 'Iwori Oturupon' },
      { descricao: 'Iwori Otura' },
      { descricao: 'Iwori Irete' },
      { descricao: 'Iwori Ose' },
      { descricao: 'Iwori Ofun' },
      { descricao: 'Odi Ogbe' },
      { descricao: 'Odi Oyeku' },
      { descricao: 'Odi Iwori' },
      { descricao: 'Odi Irosun' },
      { descricao: 'Odi Oworin' },
      { descricao: 'Odi Obara' },
      { descricao: 'Odi Okanran' },
      { descricao: 'Odi Ogunda' },
      { descricao: 'Odi Osa' },
      { descricao: 'Odi Ika' },
      { descricao: 'Odi Oturupon' },
      { descricao: 'Odi Otura' },
      { descricao: 'Odi Irete' },
      { descricao: 'Odi Ose' },
      { descricao: 'Odi Ofun' },
      { descricao: 'Irosun Ogbe' },
      { descricao: 'Irosun Oyeku' },
      { descricao: 'Irosun Iwori' },
      { descricao: 'Irosun Odi' },
      { descricao: 'Irosun Oworin' },
      { descricao: 'Irosun Obara' },
      { descricao: 'Irosun Okanran' },
      { descricao: 'Irosun Ogunda' },
      { descricao: 'Irosun Osa' },
      { descricao: 'Irosun Ika' },
      { descricao: 'Irosun Oturupon' },
      { descricao: 'Irosun Otura' },
      { descricao: 'Irosun Irete' },
      { descricao: 'Irosun Ose' },
      { descricao: 'Irosun Ofun' },
      { descricao: 'Oworin Ogbe' },
      { descricao: 'Oworin Oyeku' },
      { descricao: 'Oworin Iwori' },
      { descricao: 'Oworin Odi' },
      { descricao: 'Oworin Irosun' },
      { descricao: 'Oworin Obara' },
      { descricao: 'Oworin Okanran' },
      { descricao: 'Oworin Ogunda' },
      { descricao: 'Oworin Osa' },
      { descricao: 'Oworin Ika' },
      { descricao: 'Oworin Oturupon' },
      { descricao: 'Oworin Otura' },
      { descricao: 'Oworin Irete' },
      { descricao: 'Oworin Ose' },
      { descricao: 'Oworin Ofun' },
      { descricao: 'Obara Ogbe' },
      { descricao: 'Obara Oyeku' },
      { descricao: 'Obara Iwori' },
      { descricao: 'Obara Odi' },
      { descricao: 'Obara Irosun' },
      { descricao: 'Obara Oworin' },
      { descricao: 'Obara Okanran' },
      { descricao: 'Obara Ogunda' },
      { descricao: 'Obara Osa' },
      { descricao: 'Obara Ika' },
      { descricao: 'Obara Oturupon' },
      { descricao: 'Obara Otura' },
      { descricao: 'Obara Irete' },
      { descricao: 'Obara Ose' },
      { descricao: 'Obara Ofun' },
      { descricao: 'Okanran Ogbe' },
      { descricao: 'Okanran Oyeku' },
      { descricao: 'Okanran Iwori' },
      { descricao: 'Okanran Odi' },
      { descricao: 'Okanran Irosun' },
      { descricao: 'Okanran Oworin' },
      { descricao: 'Okanran Obara' },
      { descricao: 'Okanran Ogunda' },
      { descricao: 'Okanran Osa' },
      { descricao: 'Okanran Ika' },
      { descricao: 'Okanran Oturupon' },
      { descricao: 'Okanran Otura' },
      { descricao: 'Okanran Irete' },
      { descricao: 'Okanran Ose' },
      { descricao: 'Okanran Ofun' },
      { descricao: 'Ogunda Ogbe' },
      { descricao: 'Ogunda Oyeku' },
      { descricao: 'Ogunda Iwori' },
      { descricao: 'Ogunda Odi' },
      { descricao: 'Ogunda Irosun' },
      { descricao: 'Ogunda Oworin' },
      { descricao: 'Ogunda Obara' },
      { descricao: 'Ogunda Okanran' },
      { descricao: 'Ogunda Osa' },
      { descricao: 'Ogunda Ika' },
      { descricao: 'Ogunda Oturupon' },
      { descricao: 'Ogunda Otura' },
      { descricao: 'Ogunda Irete' },
      { descricao: 'Ogunda Ose' },
      { descricao: 'Ogunda Ofun' },
      { descricao: 'Osa Ogbe' },
      { descricao: 'Osa Oyeku' },
      { descricao: 'Osa Iwori' },
      { descricao: 'Osa Odi' },
      { descricao: 'Osa Irosun' },
      { descricao: 'Osa Oworin' },
      { descricao: 'Osa Obara' },
      { descricao: 'Osa Okanran' },
      { descricao: 'Osa Ogunda' },
      { descricao: 'Osa Ika' },
      { descricao: 'Osa Oturupon' },
      { descricao: 'Osa Otura' },
      { descricao: 'Osa Irete' },
      { descricao: 'Osa Ose' },
      { descricao: 'Osa Ofun' },
      { descricao: 'Ika Ogbe' },
      { descricao: 'Ika Oyeku' },
      { descricao: 'Ika Iwori' },
      { descricao: 'Ika Odi' },
      { descricao: 'Ika Irosun' },
      { descricao: 'Ika Oworin' },
      { descricao: 'Ika Obara' },
      { descricao: 'Ika Okanran' },
      { descricao: 'Ika Ogunda' },
      { descricao: 'Ika Osa' },
      { descricao: 'Ika Oturupon' },
      { descricao: 'Ika Otura' },
      { descricao: 'Ika Irete' },
      { descricao: 'Ika Ose' },
      { descricao: 'Ika Ofun' },
      { descricao: 'Oturupon Ogbe' },
      { descricao: 'Oturupon Oyeku' },
      { descricao: 'Oturupon Iwori' },
      { descricao: 'Oturupon Odi' },
      { descricao: 'Oturupon Irosun' },
      { descricao: 'Oturupon Oworin' },
      { descricao: 'Oturupon Obara' },
      { descricao: 'Oturupon Okanran' },
      { descricao: 'Oturupon Ogunda' },
      { descricao: 'Oturupon Osa' },
      { descricao: 'Oturupon Ika' },
      { descricao: 'Oturupon Otura' },
      { descricao: 'Oturupon Irete' },
      { descricao: 'Oturupon Ose' },
      { descricao: 'Oturupon Ofun' },
      { descricao: 'Otura Ogbe' },
      { descricao: 'Otura Oyeku' },
      { descricao: 'Otura Iwori' },
      { descricao: 'Otura Odi' },
      { descricao: 'Otura Irosun' },
      { descricao: 'Otura Oworin' },
      { descricao: 'Otura Obara' },
      { descricao: 'Otura Okanran' },
      { descricao: 'Otura Ogunda' },
      { descricao: 'Otura Osa' },
      { descricao: 'Otura Ika' },
      { descricao: 'Otura Oturupon' },
      { descricao: 'Otura Irete' },
      { descricao: 'Otura Ose' },
      { descricao: 'Otura Ofun' },
      { descricao: 'Irete Ogbe' },
      { descricao: 'Irete Oyeku' },
      { descricao: 'Irete Iwori' },
      { descricao: 'Irete Odi' },
      { descricao: 'Irete Irosun' },
      { descricao: 'Irete Oworin' },
      { descricao: 'Irete Obara' },
      { descricao: 'Irete Okanran' },
      { descricao: 'Irete Ogunda' },
      { descricao: 'Irete Osa' },
      { descricao: 'Irete Ika' },
      { descricao: 'Irete Oturupon' },
      { descricao: 'Irete Otura' },
      { descricao: 'Irete Ose' },
      { descricao: 'Irete Ofun' },
      { descricao: 'Ose Ogbe' },
      { descricao: 'Ose Oyeku' },
      { descricao: 'Ose Iwori' },
      { descricao: 'Ose Odi' },
      { descricao: 'Ose Irosun' },
      { descricao: 'Ose Oworin' },
      { descricao: 'Ose Obara' },
      { descricao: 'Ose Okanran' },
      { descricao: 'Ose Ogunda' },
      { descricao: 'Ose Osa' },
      { descricao: 'Ose Ika' },
      { descricao: 'Ose Oturupon' },
      { descricao: 'Ose Otura' },
      { descricao: 'Ose Irete' },
      { descricao: 'Ose Ofun' },
      { descricao: 'Ofun Ogbe' },
      { descricao: 'Ofun Oyeku' },
      { descricao: 'Ofun Iwori' },
      { descricao: 'Ofun Odi' },
      { descricao: 'Ofun Irosun' },
      { descricao: 'Ofun Oworin' },
      { descricao: 'Ofun Obara' },
      { descricao: 'Ofun Okanran' },
      { descricao: 'Ofun Ogunda' },
      { descricao: 'Ofun Osa' },
      { descricao: 'Ofun Ika' },
      { descricao: 'Ofun Oturupon' },
      { descricao: 'Ofun Otura' },
      { descricao: 'Ofun Irete' },
      { descricao: 'Ofun Ose' },
    ],
  })

  await prisma.classificacao.createMany({
    data: [
      { nome: 'Aiku', descricao: 'Longevidade', tipoClassificacaoId: ire.id },
      { nome: 'Ajè', descricao: 'Prosperidade', tipoClassificacaoId: ire.id },
      { nome: 'Laya/Oko', descricao: 'Esposa/Marido', tipoClassificacaoId: ire.id },
      { nome: 'Òmó', descricao: 'Filhos', tipoClassificacaoId: ire.id },
      { nome: 'Ìsé', descricao: 'Trabalho', tipoClassificacaoId: ire.id },
      { nome: 'Ilè', descricao: 'Casa', tipoClassificacaoId: ire.id },
      { nome: 'Òyé', descricao: 'Sucesso', tipoClassificacaoId: ire.id },
      { nome: 'Ìlósiwaju', descricao: 'Progresso', tipoClassificacaoId: ire.id },
      { nome: 'Àséìworí', descricao: 'Autoconfiança', tipoClassificacaoId: ire.id },
      { nome: 'Ìwàpèlé', descricao: 'Caráter Nobre', tipoClassificacaoId: ire.id },
      { nome: 'Ìfé', descricao: 'Amor', tipoClassificacaoId: ire.id },
      { nome: 'Ìgbéga', descricao: 'Respeito', tipoClassificacaoId: ire.id },
      { nome: 'Ìmò', descricao: 'Sabedoria', tipoClassificacaoId: ire.id },
      { nome: 'Ìré Gbogbo', descricao: 'Todas as Bençãos', tipoClassificacaoId: ire.id },
      { nome: 'Ìkú', descricao: 'Morte', tipoClassificacaoId: ayewoo.id },
      { nome: 'Àrun', descricao: 'Doença', tipoClassificacaoId: ayewoo.id },
      { nome: 'Èjó', descricao: 'Tristeza', tipoClassificacaoId: ayewoo.id },
      { nome: 'Òfó', descricao: 'Derrota/Perda', tipoClassificacaoId: ayewoo.id },
      { nome: 'Òran', descricao: 'Problema', tipoClassificacaoId: ayewoo.id },
      { nome: 'Ìjà', descricao: 'Briga', tipoClassificacaoId: ayewoo.id },
      { nome: 'Egbá', descricao: 'Paralizia/Dificuldade', tipoClassificacaoId: ayewoo.id },
      { nome: 'Ògún', descricao: 'Brigas e Conflitos Armados', tipoClassificacaoId: ayewoo.id },
      { nome: 'Òfó Òjuani', descricao: 'Feitiço/Maldição', tipoClassificacaoId: ayewoo.id },
      { nome: 'Asa', descricao: 'Prisão', tipoClassificacaoId: ayewoo.id },
      { nome: 'Ìbi Gbogbo', descricao: 'Todos os Males', tipoClassificacaoId: ayewoo.id },
    ],
  })
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
